apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.acceleration_a.service.name }}
  namespace: {{ .Values.acceleration_a.namespace }}
spec:
  type: {{ default "NodePort" .Values.acceleration_a.service.type }}
  selector:
    name: {{ .Values.acceleration_a.name }}
  ports:
    - port: {{ .Values.acceleration_a.ports.webport }}
      targetPort: {{ .Values.acceleration_a.ports.webport }}