# Default values for acceleration.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
#The acceleration-a microservice variables and values
acceleration_a:
#acceleration-a deployment name and namespace
  name: "acceleration-a"
  namespace: default
  replicas: 2
#acceleration-a image name, tag and credentials secret
  image: 
    repository: hemanthkumarbattula/acceleration-a
    tag: latest
    credentials:
      secretName: mycred
  pullPolicy: IfNotPresent
#acceleration-a TCP port
  ports:
    webport: 3002
#acceleration-a resource requests and limits
  resources:
    requests:
      cpu: "100m"
      memory: "1Gi"
    limits:
      cpu: "8"
      memory: "4Gi"
#acceleration-a service name and service type
  service:
    name: accelerationa-service
    type: NodePort

#The acceleration-calc microservice variables and values   
acceleration_calc:
#acceleration-calc deployment name and namespace
  name: "acceleration-calc"
  namespace: default
  replicas: 2
#acceleration-calc image name, tag and credentials secret
  image: 
    repository: hemanthkumarbattula/acceleration-calc
    tag: latest
    credentials:
      secretName: mycred
  pullPolicy: IfNotPresent
  ports:
    webport: 3000
  resources:
    requests:
      cpu: "100m"
      memory: "1Gi"
    limits:
      cpu: "8"
      memory: "4Gi"
#acceleration-calc service name and service type
  service:
    name: accelerationcalc-service
    type: ClusterIP
#acceleration-calc ingress source name
  ingress:
    name: ingress-accelerationcalc

#The acceleration-dv microservice variables and values
acceleration_dv:
  name: "acceleration-dv"
  namespace: default
  replicas: 2
  image: 
    repository: hemanthkumarbattula/acceleration-dv
    tag: latest
    credentials:
      secretName: mycred
  pullPolicy: IfNotPresent
  ports:
    webport: 3001
#acceleration-dv resource requests and limits
  resources:
    requests:
      cpu: "100m"
      memory: "1Gi"
    limits:
      cpu: "8"
      memory: "4Gi"
#acceleration-dv service name and type
  service:
    name: accelerationdv-service
    type: NodePort
